# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class Lut < Formula
  desc ""
  homepage "https://github.com/wayneashleyberry/lut"
  version "6.3.4"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/wayneashleyberry/lut/releases/download/v6.3.4/lut_6.3.4_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "fe2be651069449eaabfe9281b5fe7b3b1d55b8281964c3af1484c892fd9a8c97"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/wayneashleyberry/lut/releases/download/v6.3.4/lut_6.3.4_darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "620bab991abf6595c42e4e6e56c75dfa7a1cef37d749e97723bf39585b5e24de"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/wayneashleyberry/lut/releases/download/v6.3.4/lut_6.3.4_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "f2c9ad1912c28d39687e3634478c262a11d984dcdaf852092832f9fbd91b10e2"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/wayneashleyberry/lut/releases/download/v6.3.4/lut_6.3.4_linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "8e266858c56a1826b5a6982f63cea936b816540df61638e6e3eb52e5f3101665"
  end

  def install
    bin.install "lut"
  end

  test do
    system "#{bin}/lut version"
  end
end
